### ISSUE TITLE
Cannot get schem from GraphQL-dotnet server

### ISSUE THREAD

**Issue by Stoom** [graphcool/graphql-cli#10]
I am running the latest version of graphql-dotnet and trying to hit it via the cli's get-schema.  It keeps returning the following error: `Error trying to resolve type.: { long response }`.

**Comment by Stoom** [comment]
Here is the error section of the response
```json
{
"errors":[{"message":"Error trying to resolve type.","locations":[{"line":31,"column":7}]}],"status":400}
}
```

**Comment by Stoom** [comment]
The issue ended up being a mutation field that was of `ObjectGraphType` (void mutation).

**Comment by schickling** [comment]
Thanks for providing the answer to this. Closing this unless someone else is also having related problems.
