### ISSUE TITLE
graphql-cli vs graphcool cli?

### ISSUE THREAD

**Issue by steve-a-jones** [graphcool/graphql-cli#18]
Hi there,

New to graphql and graphcool. At a first glance i'm having trouble understanding the difference between graphql-cli and the graphcool cli projects.

Should I be using them together? If I go to the GraphCool docs for "Graphcool CLI" (https://docs-next.graph.cool/reference/basics/cli-zboghez5go) I end up `npm` installing `graphcool@beta`.

I didn't do this at first, so a simple search for graphcool cli landed me here to install a cli tool built by graphcool. I'm sure they serve different purposes, but some added clarity might help newcomers that are familiarizing themselves with the landscape.

Also, I'm seeing several dead links (Including one in the readme of this repo) pointing to "https://github.com/graphcool/graphcool-cli".

**Comment by schickling** [comment]
Thanks a lot for bringing this up @steve-a-jones! We'll be shortly writing a FAQ article about this which should give more details about what the differences are and when to use which tool.

Stay tuned!

**Comment by steve-a-jones** [comment]
Excellent! Looking forward to it! Feel free to close in favor of https://github.com/graphcool/graphcool/issues/707

**Comment by nikolasburk** [comment]
Hi @steve-a-jones! We've now added this to our FAQ section, you can take a look here: https://docs-next.graph.cool/faq/other-reob2ohph7/#whats-the-difference-between-the-graphcool-cli-and-the-graphql-cli

Does this basic explanation help to draw a line between the two?

**Comment by steve-a-jones** [comment]
Looks great @nikolasburk!

**Comment by johhansantana** [comment]
seems like the link is broken :(

**Comment by steve-a-jones** [comment]
@johhansantana - try this one: https://www.graph.cool/docs/faq/other-reob2ohph7/#whats-the-difference-between-the-graphcool-cli-and-the-graphql-cli
