### ISSUE TITLE
Schema is not syncing if I change the @relation name

### ISSUE THREAD

**Issue by welf** [graphcool/graphql-cli#35]
Hi! I've experimented with my test app and worked with GraphQL schema locally in Emacs. I've changed the `@relation` name, launched `graphcool status` and got:
```
Project ID: cj8kamumd06qv0177zzdxv53v
Remote Schema Version: 6

Everything up-to-date.
```

`graphcool push` doesn't sync schema as well. 

Is it a bug or a feature? ;)

**Comment by schickling** [comment]
This issue was moved to graphcool/graphcool#764
