### ISSUE TITLE
Deploy does not deploy field name changes

### ISSUE THREAD

**Issue by JensMadsen** [graphcool/graphql-cli#45]
running: graphcool/0.9.2 (linux-x64) node-v8.9.1

changing existing relation (here LawOnLaw) e.g. 

```
lawCites: [Law!]! @relation(name: "LawOnLaw")
lawCitesLaw: [Law!]! @relation(name: "LawOnLaw")
```
is not captured by deploy

**Comment by schickling** [comment]
Issue moved to [graphcool/framework #1273](https://github.com/graphcool/framework/issues/1273) via [**ZenHub**](https://www.zenhub.com/)
